#!/usr/bin/env bash
# a Bash Script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx start