#!/usr/bin/env bash
#Displays content of the file /etc/passwd
while IFS=':' read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND_SHELL USER ID PASSWORD USER ID INFO;
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s %s's place is protected by the passcode %s, more info about the user here: %s %s %s\n" "$USERNAME" "$GROUP_ID" "$HOME_DIRECTORY" "$COMMAND_SHELL" "$USERID" "$USER" "$ID" "$PASSWORD" "$USER" "$ID" "$INFO"                                   
done < /etc/passwd

