#!/usr/bin/env bash
#Displays content of the file /etc/passwd

IFS=':' 
while read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND_SHELL USERID PASSWORD USERIDINFO;
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$USERNAME" "$GROUP_ID" "$HOME_DIRECTORY" "$COMMAND_SHELL" "$USERID" "$PASSWORD" "$USERIDINFO"
done < /etc/passwd

