#!/usr/bin/env bash
#print str n times using while loop using if and elif statements
i=1
while [ $i -le 10 ]
do 
	if [ $i -eq 4 ]
	then
		echo "bad luck"
    elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
