#!/usr/bin/env bash
#print str n times using while loop using if and elif statements
i=1
while [ $i -le 8 ]
do 
	echo "Holberton School"
	 i=$(( i + 1 ))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
    elif [ $i -eq 7 ]
	then
		echo "good luck"
    fi
done
