#!/usr/bin/env bash
#print str n times using while loop using case statements
i=1
counter=1
while [ $i -le 20 ]
do 
	echo "$i"
	case $i in
	4)
		echo "bad luck from China"
	;;

    9)
		echo "bad luck from Japan"
	;;
	17)
		echo "bad luck from Italy"
		((counter++))
	esac
	i=$(( i + 1 ))
done
