#!/usr/bin/env bash
#print str n times using while loop using if statements
i=0

counter=1

while [ $i -le 12 ]
do 
		echo "Hour: $i"
j="1"
while [ $j -le 59 ]
do
	echo "$j"
	((counter++))

j=$((j + 1))
done
i=$((i + 1))

done
