#!/usr/bin/env bash
# a Bash Script that configures a ufw firewall to block all incoming traffic

apt-get install ufw
ufw disable
ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
