#!/usr/bin/env bash
# a Bash Script that configures nginx as nginx user
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 644 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
