#!/usr/bin/env bash
# a Bash Script that configures nginx as nginx user
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R nginx:nginx /var/www/html/index.nginx-debian.html
sudo chmod -R 644 /var/www
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
